name: Continuos Integration Workflow

on:
  pull_request:
    branches: [main, develop]

jobs:
  integrate_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint Project
        run: npm run lint

      - name: Build Project
        run: pnpm run build

      - name: Run unit tests
        run: npm run test -- --watch=false
